/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package InterfazGUI;

import Objetos.ArbolGenealogico;
import Objetos.DatosProyecto;
import Objetos.Funcion;
import Objetos.Grafos;
import Objetos.NodoArbol;
import Objetos.Persona;
import Primitivas.HashTable;
import Primitivas.Lista;
import java.awt.Graphics;
import java.awt.Image;
import javax.swing.DefaultListModel;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 * La clase InterfazFinal representa la interfaz gráfica de usuario (GUI) para interactuar con el árbol genealógico
 * Proporciona funcionalidades para cargar datos, buscar persona, generar sus antepasados, descendientes, buscar por su titulo, nombre, buscar generacion, y tambien ver descendecia y ascedencia
 * 
 * @author Ricardo Paez - Luciano Minardo - Gabriele Colarusso
 * @version 21/11/2024
 */
public class InterfazPrueba1 extends javax.swing.JFrame {
    FondoPanel fondo = new FondoPanel();
    private Grafos grafo; 
    private HashTable<String, NodoArbol> tablaPersonasPorId; // Mapea ID de persona a NodoArbol
    private HashTable<String, String> nombreAId; // Mapea nombres (incluyendo apodos y alias únicos) a IDs
    private Lista<Persona> listaPersonas; // Lista de todas las personas
    private HashTable<String, String> nombreAIdModificado;
    private ArbolGenealogico arbolGenealogico;
    private Lista<Persona> resultados;

    /**
     * Creates new form InterfazPrueba1
     */
    public InterfazPrueba1() {
        this.setContentPane(fondo);
        initComponents();
        grafo = new Grafos();
        tablaPersonasPorId = new HashTable<>();
        nombreAId = new HashTable<>();
        listaPersonas = new Lista<>();
        nombreAIdModificado = new HashTable<>();
        arbolGenealogico = new ArbolGenealogico();
        resultados = new Lista<>();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        ListadeNobilariosTitulo = new javax.swing.JList<>();
        BotonCargarJsonYGrafo = new javax.swing.JButton();
        BotonBuscarNombre = new javax.swing.JButton();
        BotonBuscarGeneracion = new javax.swing.JButton();
        BotonVerAscendencia = new javax.swing.JButton();
        TextoNombre = new javax.swing.JTextField();
        BotonGenerarSuArbol = new javax.swing.JButton();
        botonBuscarTitulo = new javax.swing.JButton();
        textoTitulo = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        textoResultados = new javax.swing.JTextArea();
        BotonListaIntegrantes = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Proyecto 2 - Arbol Genealogico");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(597, 47, -1, -1));

        ListadeNobilariosTitulo.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                ListadeNobilariosTituloValueChanged(evt);
            }
        });
        jScrollPane2.setViewportView(ListadeNobilariosTitulo);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 520, 210, 128));

        BotonCargarJsonYGrafo.setBackground(new java.awt.Color(204, 204, 255));
        BotonCargarJsonYGrafo.setFont(new java.awt.Font("Impact", 0, 24)); // NOI18N
        BotonCargarJsonYGrafo.setText("Cargar Json Y Graficar Arbol");
        BotonCargarJsonYGrafo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonCargarJsonYGrafoActionPerformed(evt);
            }
        });
        getContentPane().add(BotonCargarJsonYGrafo, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 70, -1, 63));

        BotonBuscarNombre.setBackground(new java.awt.Color(204, 204, 255));
        BotonBuscarNombre.setFont(new java.awt.Font("Impact", 0, 18)); // NOI18N
        BotonBuscarNombre.setText("Buscar Nombre");
        BotonBuscarNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonBuscarNombreActionPerformed(evt);
            }
        });
        getContentPane().add(BotonBuscarNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 680, -1, 44));

        BotonBuscarGeneracion.setBackground(new java.awt.Color(204, 204, 255));
        BotonBuscarGeneracion.setFont(new java.awt.Font("Impact", 0, 18)); // NOI18N
        BotonBuscarGeneracion.setText("Buscar Generacion");
        BotonBuscarGeneracion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonBuscarGeneracionActionPerformed(evt);
            }
        });
        getContentPane().add(BotonBuscarGeneracion, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 740, -1, 42));

        BotonVerAscendencia.setBackground(new java.awt.Color(204, 204, 255));
        BotonVerAscendencia.setFont(new java.awt.Font("Impact", 0, 18)); // NOI18N
        BotonVerAscendencia.setText("Ver Ascendencia");
        BotonVerAscendencia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonVerAscendenciaActionPerformed(evt);
            }
        });
        getContentPane().add(BotonVerAscendencia, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 680, -1, 44));
        getContentPane().add(TextoNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 210, 417, 44));

        BotonGenerarSuArbol.setBackground(new java.awt.Color(204, 204, 255));
        BotonGenerarSuArbol.setFont(new java.awt.Font("Impact", 0, 18)); // NOI18N
        BotonGenerarSuArbol.setText("Generar arbol descendientes");
        BotonGenerarSuArbol.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonGenerarSuArbolActionPerformed(evt);
            }
        });
        getContentPane().add(BotonGenerarSuArbol, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 260, -1, 60));

        botonBuscarTitulo.setBackground(new java.awt.Color(204, 204, 255));
        botonBuscarTitulo.setFont(new java.awt.Font("Impact", 0, 18)); // NOI18N
        botonBuscarTitulo.setText("Buscar Titulo");
        botonBuscarTitulo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonBuscarTituloActionPerformed(evt);
            }
        });
        getContentPane().add(botonBuscarTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 740, 144, 42));

        textoTitulo.setFont(new java.awt.Font("Segoe UI Semibold", 0, 12)); // NOI18N
        textoTitulo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textoTituloActionPerformed(evt);
            }
        });
        getContentPane().add(textoTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 470, 523, 41));

        textoResultados.setColumns(20);
        textoResultados.setRows(5);
        jScrollPane1.setViewportView(textoResultados);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 520, 357, 128));

        BotonListaIntegrantes.setBackground(new java.awt.Color(204, 204, 255));
        BotonListaIntegrantes.setFont(new java.awt.Font("Impact", 0, 18)); // NOI18N
        BotonListaIntegrantes.setText("Ver Descendencia");
        BotonListaIntegrantes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonListaIntegrantesActionPerformed(evt);
            }
        });
        getContentPane().add(BotonListaIntegrantes, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 680, 174, 44));

        jButton1.setBackground(new java.awt.Color(204, 204, 255));
        jButton1.setFont(new java.awt.Font("Impact", 0, 18)); // NOI18N
        jButton1.setText("Generar arbol antepasados");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 260, 244, 58));

        jLabel2.setFont(new java.awt.Font("Segoe UI Semibold", 0, 12)); // NOI18N
        jLabel2.setText("Selecciona un boton que deas usar: Generar Árbol de descendientes o el de antepasados");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 180, -1, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI Semibold", 0, 12)); // NOI18N
        jLabel3.setText("Introduce un nombre, titulo o un numero para buscar la generacion correspondiente");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 360, -1, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI Semibold", 0, 12)); // NOI18N
        jLabel4.setText("Selecciona el Json que deseas cargar para mostrar su Árbol Genealógico");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 40, -1, -1));

        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(597, 116, -1, -1));

        jLabel9.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        jLabel9.setText("Para este text field, es necesario ingresar el nombre completo de la persona.");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 0, 0));

        jLabel10.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        jLabel10.setText("Un ejemplo valido es: William Baratheon, First of his name.");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 0, 0));

        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(763, 116, -1, -1));

        jLabel11.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        jLabel11.setText("Para este text field, a la hora de ver ascendencias y descendencias, es recomendable");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 0, 0));

        jLabel12.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        jLabel12.setText("escribir el nombre completo de la persona en caso de que hayan varios con el mismo nombre");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 0, 0));

        jLabel5.setFont(new java.awt.Font("Segoe UI Semibold", 0, 12)); // NOI18N
        jLabel5.setText("Un ejemplo valido es: William Baratheon, First of his name.");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 400, -1, -1));

        jLabel6.setFont(new java.awt.Font("Segoe UI Semibold", 0, 12)); // NOI18N
        jLabel6.setText("Para buscar por titulo es necesario el titulo completo. Ej: Knight of the Kingsguard.");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 420, -1, -1));

        jLabel7.setFont(new java.awt.Font("Segoe UI Semibold", 0, 12)); // NOI18N
        jLabel7.setText("Para buscar por nombre no es necesario el nombre completo. ");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 380, -1, -1));

        jLabel8.setFont(new java.awt.Font("Segoe UI Semibold", 0, 12)); // NOI18N
        jLabel8.setText("Para buscar por generacion es necesario introducir un numero entero valido.");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 440, -1, -1));

        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(351, 868, -1, -1));

        jLabel1.setFont(new java.awt.Font("Segoe UI Semibold", 0, 12)); // NOI18N
        jLabel1.setText("Ingresa un nombre que  deseas ver su antepasado o descendientes");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 160, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ListadeNobilariosTituloValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_ListadeNobilariosTituloValueChanged
        if (!evt.getValueIsAdjusting()) { // Evita manejar eventos múltiples al cambiar selección
            int indiceSeleccionado = ListadeNobilariosTitulo.getSelectedIndex();
            if (indiceSeleccionado != -1) {
                Persona personaSeleccionada = resultados.get(indiceSeleccionado);
                // Mostrar detalles en un JTextArea o ventana emergente
                textoResultados.setText("Detalles de la persona seleccionada:\n" + personaSeleccionada.toString());
            }
        }
    }//GEN-LAST:event_ListadeNobilariosTituloValueChanged

    private void BotonCargarJsonYGrafoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonCargarJsonYGrafoActionPerformed
        DatosProyecto datos = Funcion.leerJsonConFileChooser();
        Lista<Persona> personas = datos.getPersonas();

        if (personas != null && personas.getSize() > 0) {
            Grafos nuevoGrafo = new Grafos();
            nuevoGrafo.mostrarArbol(arbolGenealogico);

            // Construir el árbol genealógico y agregar los arcos al grafo
            arbolGenealogico.construirArbol(personas, nuevoGrafo);

            // Construir la tabla de nombres modificados
            arbolGenealogico.construirTablaNombreModificado();
        }
    }//GEN-LAST:event_BotonCargarJsonYGrafoActionPerformed

    private void BotonBuscarNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonBuscarNombreActionPerformed
        String nombreBusqueda = textoTitulo.getText().trim();
        if (nombreBusqueda.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Por favor, ingresa un nombre o mote válido.");
            return;
        }
        resultados = arbolGenealogico.buscarPorNombreParcial(nombreBusqueda);
        if (resultados.getSize() == 0) {
            JOptionPane.showMessageDialog(this, "No se encontraron personas con ese nombre o mote.");
            return;
        }
        // Crear un modelo para el JList
        DefaultListModel<String> modeloLista = new DefaultListModel<>();
        for (int i = 0; i < resultados.getSize(); i++) {
            Persona persona = resultados.get(i);
            modeloLista.addElement(persona.getNombre()); // Mostrar solo el nombre
        }
        // Asignar el modelo al JList
        ListadeNobilariosTitulo.setModel(modeloLista);
        JOptionPane.showMessageDialog(this, "Selecciona un registro para ver más detalles.");
    }//GEN-LAST:event_BotonBuscarNombreActionPerformed

    private void BotonBuscarGeneracionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonBuscarGeneracionActionPerformed
        try {
            int numeroGeneracion = Integer.parseInt(textoTitulo.getText().trim());

            if (numeroGeneracion < 0) {
                JOptionPane.showMessageDialog(this, "El número de generación debe ser mayor o igual a 0.");
                return;
            }

            // Obtener la altura del árbol
            int alturaArbol = arbolGenealogico.obtenerAltura();

            if (numeroGeneracion >= alturaArbol) {
                JOptionPane.showMessageDialog(this, "El número de generación supera la altura del árbol genealógico (" + (alturaArbol-1) + ").");
                return;
            }

            // Obtener los resultados de la generación solicitada
            resultados = arbolGenealogico.obtenerPersonasGeneracion(numeroGeneracion);

            if (resultados.getSize() == 0) {
                JOptionPane.showMessageDialog(this, "No se encontraron personas en la generación solicitada.");
                return;
            }

            // Crear un modelo para el JList
            DefaultListModel<String> modeloLista = new DefaultListModel<>();
            for (int i = 0; i < resultados.getSize(); i++) {
                Persona persona = resultados.get(i);
                modeloLista.addElement(persona.getNombre()); // Mostrar solo el nombre
            }

            // Asignar el modelo al JList
            ListadeNobilariosTitulo.setModel(modeloLista);
            JOptionPane.showMessageDialog(this, "Selecciona un registro para ver más detalles.");
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Por favor, ingresa un número válido para la generación.");
        }
    }//GEN-LAST:event_BotonBuscarGeneracionActionPerformed

    private void BotonVerAscendenciaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonVerAscendenciaActionPerformed
        String nombreBusqueda = textoTitulo.getText().trim();

        if (nombreBusqueda.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Por favor, ingresa un nombre válido.");
            return;
        }

        Lista<Persona> resultados = arbolGenealogico.buscarPorNombreParcial(nombreBusqueda);

        if (resultados.getSize() == 0) {
            JOptionPane.showMessageDialog(this, "No se encontró ninguna persona con el nombre: " + nombreBusqueda);
            return;
        }

        Persona personaSeleccionada = resultados.get(0);

        String descendencia = arbolGenealogico.obtenerAscendenciaOrdenada(personaSeleccionada.getNombre());
        String descendenciaSinCorchetes = descendencia.replace("[", "").replace("]", "");

        textoResultados.setText(descendenciaSinCorchetes);
    }//GEN-LAST:event_BotonVerAscendenciaActionPerformed

    private void BotonGenerarSuArbolActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonGenerarSuArbolActionPerformed
        String nombrePersona = TextoNombre.getText();
        if (nombrePersona == null || nombrePersona.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Por favor ingresa un nombre válido.");
            return;
        }

        // **Create a new Grafos instance**
        Grafos nuevoGrafo = new Grafos();
        nuevoGrafo.mostrarArbol(arbolGenealogico);

        // Generate the descendants graph
        arbolGenealogico.mostrarArbolGenealogicoPorNombre(nombrePersona, nuevoGrafo);
    }//GEN-LAST:event_BotonGenerarSuArbolActionPerformed

    private void botonBuscarTituloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonBuscarTituloActionPerformed
        String tituloBusqueda = textoTitulo.getText().trim();
        if (tituloBusqueda.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Por favor, ingresa un título válido.");
            return;
        }
        resultados = arbolGenealogico.buscarPorTitulo(tituloBusqueda);
        if (resultados.getSize() == 0) {
            JOptionPane.showMessageDialog(this, "No se encontraron personas con ese título.");
            return;
        }
        // Crear un modelo para el JList
        DefaultListModel<String> modeloLista = new DefaultListModel<>();
        for (int i = 0; i < resultados.getSize(); i++) {
            Persona persona = resultados.get(i);
            modeloLista.addElement(persona.getNombre()); // Mostrar solo el nombre
        }
        // Asignar el modelo al JList
        ListadeNobilariosTitulo.setModel(modeloLista);
        JOptionPane.showMessageDialog(this, "Selecciona un registro para ver más detalles.");
    }//GEN-LAST:event_botonBuscarTituloActionPerformed

    private void textoTituloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textoTituloActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textoTituloActionPerformed

    private void BotonListaIntegrantesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonListaIntegrantesActionPerformed
        String nombreBusqueda = textoTitulo.getText().trim();

        if (nombreBusqueda.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Por favor, ingresa un nombre válido.");
            return;
        }

        Lista<Persona> resultados = arbolGenealogico.buscarPorNombreParcial(nombreBusqueda);

        if (resultados.getSize() == 0) {
            JOptionPane.showMessageDialog(this, "No se encontró ninguna persona con el nombre: " + nombreBusqueda);
            return;
        }

        Persona personaSeleccionada = resultados.get(0);

        String descendencia = arbolGenealogico.obtenerDescendenciaOrdenada(personaSeleccionada.getNombre());

        textoResultados.setText(descendencia);
    }//GEN-LAST:event_BotonListaIntegrantesActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        String nombrePersona = TextoNombre.getText();
        if (nombrePersona == null || nombrePersona.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Por favor ingresa un nombre válido.");
            return;
        }

        Grafos nuevoGrafo = new Grafos();
        nuevoGrafo.mostrarArbol(arbolGenealogico);

        // Llamar al método para mostrar el árbol genealógico de esa persona
        arbolGenealogico.mostrarAntepasados(nombrePersona, nuevoGrafo);
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BotonBuscarGeneracion;
    private javax.swing.JButton BotonBuscarNombre;
    private javax.swing.JButton BotonCargarJsonYGrafo;
    private javax.swing.JButton BotonGenerarSuArbol;
    private javax.swing.JButton BotonListaIntegrantes;
    private javax.swing.JButton BotonVerAscendencia;
    private javax.swing.JList<String> ListadeNobilariosTitulo;
    private javax.swing.JTextField TextoNombre;
    private javax.swing.JButton botonBuscarTitulo;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea textoResultados;
    private javax.swing.JTextField textoTitulo;
    // End of variables declaration//GEN-END:variables
        
    class FondoPanel extends JPanel
    {
        private Image imagen;
        
        @Override
        public void paint(Graphics g)
        {
            imagen = new ImageIcon(getClass().getResource("/Imagenes/ImagenFondoInterfaz.jpg")).getImage();
            
            g.drawImage(imagen, 0, 0, getWidth(), getHeight(), this);
            
            setOpaque(false);
            
            super.paint(g);
        }
    }
}
